// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jyjuifmmruytnsvjyghl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5anVpZm1tcnV5dG5zdmp5Z2hsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg4MjM3NjUsImV4cCI6MjA5NDM5OTc2NX0.rY0W2_YI3b0d0E5I47rmBnPgdiAsAPp2Nu9LvKSM4tY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL || 'https://placeholder.supabase.co', SUPABASE_PUBLISHABLE_KEY || 'placeholder', {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});